export default {
    products: [
        {
            _id: '1',
            name: 'Cama 2 plazas + 2 Veladores + Respaldo',
            category: 'Camas',
            image: '/img/1141461F12.webp',
            price: '149.990',
            brand: 'CIC',
            rating: 4.0,
            numReviews: 18,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Cama Europea King + 2 Veladores + Respaldo',
            category: 'Camas',
            image: '/img/1144431f13.webp',
            price: '849.990',
            brand: 'ROSE',
            rating: 5,
            numReviews: 31,
            countInStock: 5,
        },
        {
            _id: '3',
            name: 'Cama Europea King + Respaldo Milán',
            category: 'Camas',
            image: '/img/1151842f13.webp',
            price: '489.990',
            brand: 'CIC',
            rating: 4.5,
            numReviews: 24,
            countInStock: 3,
        },
        {
            _id: '4',
            name: 'Smart TV 50" 4K',
            category: 'SmartTV',
            image: '/img/1143659F12.webp',
            price: '349.990',
            brand: 'SAMSUNG',
            rating: 4.5,
            numReviews: 10,
            countInStock: 8,
        },
        {
            _id: '5',
            name: 'Smart TV 48" 4K',
            category: 'SmartTV',
            image: '/img/1149638f13.webp',
            price: '329.990',
            brand: 'LG',
            rating: 4.7,
            numReviews: 18,
            countInStock: 12,
        },
        {
            _id: '6',
            name: 'Smart TV 43" Full HD',
            category: 'SmartTV',
            image: '/img/1150575f13.webp',
            price: '189.990',
            brand: 'AOC',
            rating: 3.7,
            numReviews: 10,
            countInStock: 7,
        },
    ],
};